services:
  # web server
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./stack/nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence
    ports:
      - 443:443
    env_file:
      - .env
    secrets:
      - Certificate
      - Key
    restart: always
  # website front
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./stack/frontend
      dockerfile: Dockerfile
    depends_on:
      - pgdb
    networks:
      - transcendence
    env_file:
      - .env
    restart: always
# website back
  backend:
    container_name: backend
    image: backend
    build:
      context: ./stack/backend
      dockerfile: Dockerfile
    depends_on:
      pgdb:
        condition: service_healthy
    networks:
      - transcendence
    env_file:
      - .env
    environnement:
      DATABASE_URL: postgresql://${PGSQL_USER}:${PGSQL_PASSWORD}@pgdb:5432/${PGSQL_DATABASE}?schema=public
    restart: always
  # database
  pgdb:
    container_name: pgdb
    image: pgdb
    build:
      context: ./stack/pgdb
      dockerfile: Dockerfile
    networks:
      - transcendence
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DATABASE}
    volumes:
      - pgdb_data: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/data/pgdb_data

networks:
  transcendence:
    driver: bridge
  
secrets:
  Certificate:
    file: ../secrets/transcendence.crt
  Key:
    file: ../secrets/transcendence.key