events {}

http {
	include /etc/nginx/mime.types;
	server {
		#SSL/TLS Configuration
		listen 443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /run/secrets/Certificate;
		ssl_certificate_key /run/secrets/Key;

		# server_name
		server_name clmmm.42.fr;

		#root and index 
		root /var/www/html;
		index index.php index.nginx-debian.html index.htm;

		location / {
			try_files $uri /index.php?$args;
		}

		location ~* .(css|js|jpg|jpeg|png|gif|ico|svg|webp|woff|woff2|ttf|eot)$ {
			try_files $uri =404;
			expires 6M;
			access_log off;
		}
		
		location ~ .php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
		}
	}
}
